### ISSUE TITLE
Commenting and annotation overview

### ISSUE THREAD

**Issue by ellisonbg** [jupyterlab/jupyterlab-commenting#3]
This issue provides an overview of our vision for a universal commenting and annotation system for JupyterLab.

## Background

Since the very early days of the IPython/Jupyter Notebook we have gotten received requests to have real-time collaboration and commenting and annotation that integrates with that. These are two closely related aspects of the broader collaboration picture in Jupyter.

## Big picture

The big picture we envision has a a lot of similarity with the basic experience of Google Drive, but with some important differences:

* JupyterLab has many different types of documents (notebooks, text files) and activities (visualizations, terminals, consoles, etc.).
* Some of those documents are portable and can move between different systems where storage mechanisms, identities, etc. differ.
* As JupyterLab gains more capabilities, there is a strong need to maintain a user experience that doesn't overwhelm the user and remains simple.
* The state of comments in relation to a documents history is of particular importance.

## Initial design work

Over the summer of 2018 a team of design interns at Cal Poly worked on the design of the commenting and annotation system and presented their work as a poster at JupyterCon 2018. While there is more to do, this team made really good progress on the design. A separate issue(s) will be opened on the details of this work.

**Comment by bollwyvl** [comment]
Reiterating the comments (ha) from the other issue on jlab, in considering the data model, I would pass on the schema.org [Comment](https://schema.org/Comment) and have a look at the [W3C Web Annotation Data Model](https://www.w3.org/TR/annotation-model/). It already has support for almost anything we can throw at it: text, tables, images, etc. [hypothesis](https://github.com/hypothesis/h) is the main python implementation I know of (pyramid-based), and would have some great starting points, like their [schemas](https://github.com/hypothesis/h/blob/master/h/schemas/annotation.py) (colander-based). Their [sphinx-based docs](https://h.readthedocs.io/en/latest/) are a pretty good showcase of how their stuff works, but their stuff can ride along on any page through a proxy, like, i dunno:

https://via.hypothes.is/https://github.com/jupyterlab/jupyterlab-commenting/issues/3

Back in Jupyter, a big challenge (aside from the mentioned portability of datasets), is a way to point at _some thing_ in JSON (e.g. nbformat), but specifically a thing in a list like a cell or an output. The general guidance is to use a [fragment selector](https://www.w3.org/TR/annotation-model/#fragment-selector) pattern. [JSON Pointer](https://tools.ietf.org/html/rfc6901) is widely implemented, and combined with selector refinement, would be sufficient for most of our purposes:

```yaml
{
  "id": "http://hub.example.org/anno29",
  "type": "Annotation",
  "body": "http://hub.example.org/comment1",
  "target": {
    "source": "https://raw.githubusercontent.com/jupyterlab/jupyterlab/86c6a89/examples/vega/vega-extension.ipynb",
    "selector": {
      "type": "FragmentSelector",
      "value": "jsonpointer(/cells/4/outputs/0/data/image~1png)",
      "refinedBy": {
        "type": "FragmentSelector",
        "value": "xywh=0,0,100,239"
      }
    }
  }
}
```
Of course, the above only works for known, static cell/output positions in the document that won't change... but except for the very special case of annotations stored in the notebook themselves, this is fine. Most formats won't let you cram random JSON into them :P

Another approach would be [CSS selectors](https://www.w3.org/TR/annotation-model/#css-selector), but I wouldn't touch them for anything other than static, archival-grade output (e.g. nbconvert/nbsphinx output) and only then if it was _also_ cryptographically identifiable.
